version: '3.8'
services:
  service:
    build: .
    container_name: service
    hostname: service
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./src/:/app/library/src/
      - .env/:/app/library/.env
    restart: unless-stopped
    depends_on: 
      - mongo1
  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - dbdata1:/data/db

networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata1:
    driver: local