@host = 'localhost'
@port= 3000
@contentType = application/json

#Creating New Book
POST http://localhost:3000/library
content-type: {{contentType}}

{
    "title":"newBook",
    "author":"testAuthor"
}

###
# Trying to create again with same name should throw error

POST http://localhost:3000/library
content-type: {{contentType}}

{
    "title":"newBook",
    "author":"testAuthor"
}

# getting the books
###

GET http://localhost:3000/library?page=1&count=1

###
# Get 1 book by ID
GET http://localhost:3000/library/01HEK1XGS6D3YJ7A0XJAYHJFDV

###
# update 1 book ID
PATCH http://localhost:3000/library/01HEK1XGS6D3YJ7A0XJAYHJFDV
content-type: {{contentType}}

{
    "title":"new Book"
}

###
# update 1 book ID checking body validations
PATCH http://localhost:3000/library/01HEK1XGS6D3YJ7A0XJAYHJFDV
content-type: {{contentType}}

{
    "title":1
}

###
# delete 1 book which does not exists
DELETE  http://localhost:3000/library/01HEK1XGS6D3YJ7A0XJAYHJFD

###
# delete 1 book with id
DELETE  http://localhost:3000/library/01HEK1XGS6D3YJ7A0XJAYHJFDV